# Generated by Django 5.2 on 2025-04-12 09:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogreview',
            name='review',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
