# Generated by Django 5.2 on 2025-04-10 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=225, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners')),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_category', to='category.productcategory')),
                ('parent', models.ForeignKey(limit_choices_to={'parent__isnull': True}, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='banner.productbanner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
